- title: Email
  alwaysvisible: clark.winkelmann@gmail.com
  url: mailto:clark.winkelmann@gmail.com
  icon: fas fa-envelope
- title: GitHub
  url: https://github.com/clarkwinkelmann
  icon: fab fa-github
- title: Twitter
  url: https://twitter.com/clarkwinkelmann
  icon: fab fa-twitter
- title: Telegram
  url: https://telegram.me/clarkwinkelmann
  icon: fab fa-telegram
- title: Discord Clark#1615
  url: #
  icon: fab fa-discord
- title: Keybase
  url: https://keybase.io/clarkwinkelmann
  icon: fab fa-keybase
