- title: Email
  username: clark.winkelmann@gmail.com
  url: mailto:clark.winkelmann@gmail.com
  icon: envelope
- title: GitHub
  username: clarkwinkelmann
  url: https://github.com/clarkwinkelmann
  icon: github
- title: Twitter
  username: clarkwinkelmann
  url: https://twitter.com/clarkwinkelmann
  icon: twitter
- title: Telegram
  username: clarkwinkelmann
  url: https://telegram.me/clarkwinkelmann
  icon: telegram
- title: Gitter
  username: clarkwinkelmann
  url: https://gitter.im/clarkwinkelmann
  icon: comments
- title: Keybase
  username: clarkwinkelmann
  url: https://keybase.io/clarkwinkelmann
  icon: key